
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

email.user=norasrinurulyasmin@gmail.com
email.password=rzmv upky usbc vcqi
calendar.id=13946c8f578f2edf75e45ebcaa2ab14b73d932f0a5020d349fd37d8375139306@group.calendar.google.com
